var locModel = {
	"markers": [],
	"locations" : [
		{
			"name": "Chantek",
			"address": "",
			"coords": [50.263786, -5.048547],
			"description": "",
			"imgSrc": "",
			"imgAlt": "Smart modern restaurant with courtyard and open kitchen," + 
				" serving Thai and South-East Asian dishes. - Google",
			"type": "Restaurant",
			"keywords": ["ASIAN"],
			"id": 1,
			"api": false,
			"endpoint": "4c61b4ab86b6be9ae5568a34"
		},
		{
			"name": "Habanero's Burrito Bar",
			"address": "",
			"coords": [50.262962, -5.055009],
			"description": "",
			"imgSrc": "",
			"imgAlt": "Truro's only authentic Burrito spot.",
			"type": "Restaurant",
			"keywords": ["MEXICAN", "FAST FOOD", "STREET FOOD"],
			"id": 2,
			"api": false,
			"endpoint": "55cb3030498ef054bdb34605"
		},
		{
			"name": "Sonder Cafe Bar",
			"address": "",
			"coords": [50.263139, -5.049306],
			"description": "",
			"imgSrc": "",
			"imgAlt": "Truro’s first and only independent craft beer bar.",
			"type": "Restaurant",
			"keywords": ["BAR & GRILL"],
			"id": 3,
			"api": false,
			"endpoint": "56f98728498ed2f78a0e9315"
		},
		{
			"name": "Pierro's Pizzeria",
			"address": "",
			"coords": [50.263132, -5.054528],
			"description": "",
			"imgSrc": "",
			"imgAlt": "Family-oriented traditional Italian cuisine.",
			"type": "Restaurant",
			"keywords": ["ITALIAN"],
			"id": 4,
			"api": false,
			"endpoint": "4babb3aff964a520e2c13ae3"
		},
		{
			"name": "Mustard and Rye",
			"address": "",
			"coords": [50.262301, -5.054735],
			"description": "",
			"imgSrc": "",
			"imgAlt": "BBQ, steaks and shakes in sleek American-themed diner with yellow leather booths and vintage photos. - Google",
			"type": "Restaurant",
			"keywords": ["BAR & GRILL", "BBQ", "BURGER"],
			"id": 5,
			"api": false,
			"endpoint": "523d9ece498e057b77a72e45"
		},
		{
			"name": "Hubbox",
			"address": "",
			"coords": [50.263206, -5.054040],
			"description": "",
			"imgSrc": "",
			"imgAlt": "BURGERS - DOGS - BEERS",
			"type": "Restaurant",
			"keywords": ["BURGER", "BAR & GRILL"],
			"id": 6,
			"api": false,
			"endpoint": "53fb5b67498e83054e356060"
		},
		{
			"name": "Truro Cathedral",
			"address": "",
			"coords": [50.264117, -5.051248],
			"description": "",
			"imgSrc": "",
			"imgAlt": "Victorian Gothic Revival CofE place of worship with a coffee shop and restaurant plus a gift shop. - Google",
			"type": "Tourist Attraction",
			"keywords": ["HERITAGE"],
			"id": 7,
			"api": false,
			"endpoint": "4bfce39e55539c74468bbcf3"
		},
		{
			"name": "Hall For Cornwall",
			"address": "",
			"coords": [50.262668, -5.050578],
			"description": "",
			"imgSrc": "",
			"imgAlt": "Live music, drama, dance and comedy, including international touring productions, plus annual panto. - Google",
			"type": "Tourist Attraction",
			"keywords": ["ENTERTAINMENT"],
			"id": 8,
			"api": false,
			"endpoint": "4bab3ec2f964a520729b3ae3"
		},
		{
			"name": "Lemon Quay",
			"address": "",
			"coords": [50.262514, -5.051240],
			"description": "",
			"imgSrc": "",
			"imgAlt": "Truro's main plaza.",
			"type": "Tourist Attraction",
			"keywords": ["PLAZA"],
			"id": 9,
			"api": false,
			"endpoint": "4c95185594a0236a64fb9212"
		},
		{
			"name": "Royal Cornwall Museum",
			"address": "",
			"coords": [50.263681, -5.054862],
			"description": "",
			"imgSrc": "",
			"imgAlt": "Museum with minerals from around the globe and exhibits about the region's wildlife and history. - Google",
			"type": "Tourist Attraction",
			"keywords": ["HERITAGE"],
			"id": 10,
			"api": false,
			"endpoint": "4bc33143abf49521e95ec393"
		}
	],	
};